### ISSUE TITLE
Example for custom template for generating Java code from ZDL

### ISSUE THREAD

**Issue by michael-schnell** [ZenWave360/zenwave-sdk#18]
I like the Zenwave Domain Model language and would like to create a custom template for it.

Is there any example code on how to create a custom template that can be seamlessly integrated into your generator framework?

I'd like to generate some specialized Java files from the ZDL definition files.

**Comment by ivangsa** [comment]
Hi @michael-schnell 

the sdk is built with customization in mind but I didn't explore it yet... but it certainly can be done

It will require to create a maven artifact for your generator/templates and then add that new artifact to your jbang alias

It depends if you just need customize son minor changes to an existing template, you can create a maven artifact with just that template and then make sure you add it to the jbang classpath just before the original plugin

If you need bigger customization you can duplicate the contents of an existing plugin, refactor package and groupId/artifactIds and proceed to do the customization... There is an command that can assist you in that duplication (but understand that is just an aid, it will produce an artifact that still needs work to build/compile) 
https://github.com/ZenWave360/zenwave-sdk?tab=readme-ov-file#forking-an-standard-or-custom-plugin

If you use that script make sure you configure `downloadURL` because it may be a bit outdated...

And if you need more help in the process just let me know... 
Thanks for using ZenWave and Happy Hacking!!

**Comment by michael-schnell** [comment]
Tnx. I will try copying one of the plugins and then adjust it.
